### PR TITLE
Add "geo", "tel", and "sms" uri schemes

### PR DESCRIPTION
**Pull request by cepm-nate**
Allowing these three would bring Caja into the modern era of mobile web usage.

Please consider it.

### CODE REVIEW

**Comment by kpreid** [comment]
`UriPolicyNanny` is old code; if this change has an effect then you're using the old ES5/3 branch which you should not be.

The place you want to update is in the top of domado.js, `ALLOWED_URI_SCHEMES`.

Also, please sign the CLA and ensure that your pull request has exactly one rebased commit.

**Comment by kpreid** [comment]
Please squash to a single commit, correct spelling in your commit messages, and sign the CLA.

**Comment by cepm-nate** [comment]
Working on it.

**Comment by cepm-nate** [comment]
ok, I've got it all in one commit now. I'm not sure why this pull request is not updating to show that.

Also, I've signed the first CLA as my company "Cutting Edge Plumbing & Mechanical".

**Comment by kpreid** [comment]
Also, please make sure you've entered your GitHub username in the CLA agreement.

**Comment by cepm-nate** [comment]
I've signed it with the same e-mail and username, and have also changed the commit description.

**Pull request merged**
