### PR TITLE
Improve support of CSS Color Module Level 4

### LINKED ISSUE #1918: Whitelist HSL color notation in CSS
Original [issue 1920](https://code.google.com/p/google-caja/issues/detail?id=1920) created by riel@zzapps.nl on 2014-05-16T08:21:03.000Z:

<b>What revision of the cajoler exhibits the problem?  On what browser and OS?</b>

Caja Playground
Rev 5643 built on 2013-12-05 14:54:08.
ChromeOS
Versie 35.0.1916.69
Platform 5712.35.0 (Official Build) stable-channel stumpy
Firmware Google_Stumpy.2.102.0

<b>What steps will reproduce the problem?</b>
1. Change backgroundcolor using HSL values with Javascript
2. document.getElementById(&quot;myDIV&quot;).style.backgroundColor = &quot;hsl(59,100%,50%)&quot;;
3. Console gives error &quot;bad value `hsl(59,100%,50%)` for CSS property backgroundColor &quot;

What is the expected output? 
- Changing background color

Setting colors using HSL is very easy programmatically, i.e. a color bar. Cannot be used using HTMLService in GAS.

What do you see instead?
- Error message in console

<b>Please provide any additional information below.</b>

--- source ----

&lt;style&gt; 
# myDIV

{
width:300px;
height:300px;
background-color:coral;
color:white;
}
&lt;/style&gt;
&lt;div id=&quot;myDIV&quot;&gt;
&lt;h1&gt;Hello&lt;/h1&gt;
&lt;/div&gt;
&lt;script&gt;
document.getElementById(&quot;myDIV&quot;).style.backgroundColor = &quot;hsl(59,100%,50%)&quot;;
&lt;/script&gt;

​

### PR DESCRIPTION
**Pull request by Slayer95**
Extends the ``<color>`` signature to
- Allow named colors from CSS Color Module Level 4, including ``currentcolor``.
- Allow alpha channel in hexadecimal color notation (``#FFF8``, ``#33333333``).
- Support HSL and HSLA notations (Fixes #1918)

Internally, this adds definitions for ``<rgb-color>``, ``<rgba-color>``, ``<hsl-color>`` and ``<hsla-color>``.
This is useful for better maintainability, keeping in sight the proposals to extend their syntax to accept space-separated arguments, as well as new color functions.

### CODE REVIEW

**Comment by Slayer95** [comment]
Let me know if you'd prefer for me to squash these commits (although Github has squash-merge support now), or if there is anything I could improve.

**Comment by Slayer95** [comment]
Q: Is there a preferred timeframe for a new version being released in the [Caja Playground](https://caja.appspot.com/) ?

**Comment by kpreid** [comment]
De facto, it's “whenever there's a security patch”. Which isn't great, yes.

If you need a test instance you can run one locally using the command `ant runserver`.

**Comment by Slayer95** [comment]
I was actually looking for an official compiled version of the HTML sanitizer, but I might as well use my own. Thanks!

**Pull request merged**
