### PR TITLE
fixes closure compiler errors as reported by john lenz.

### PR DESCRIPTION
**Pull request by mikesamuel**
This involves fixing the Linter to allow @typedefs through since the tag policy function types become unwieldy otherwise.

### CODE REVIEW

**Comment by mikesamuel** [comment]
This is related to https://github.com/google/caja/issues/1982

**Comment by erights** [comment]
LGTM modulo review comments I just made. But please check with Kevin first before merging this pull request. I think Kevin wants changes to go through a different process involving codereview.appspot.

Kevin?

**Comment by jasvir** [comment]
+1  Kevin - I'd like to move ahead with the pull request unless you still see a reason not to.

**Comment by mikesamuel** [comment]
+kpreid, ping

**Comment by mikesamuel** [comment]
@kpreid, ping to make sure this hasn't gotten lost in the shuffle.

**Comment by kpreid** [comment]
Pushed as 27248d0f223038346d63278b52ec038e77418ba9.

**Pull request closed without merging**
